### ISSUE TITLE
Introduce yourself!

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/sandbox#1]
This is an example issue that I created for the purpose of getting folks familiar with Github.

Please comment below to introduce yourself, and use the features available in the comment area! Feel free to ask questions as well and I'll do my best to answer them.

**Comment by floppytoes** [comment]
hey Matt, great intro/overview!  thanks for doing this.  And this is Jeremy, using my "legacy" github account.

**Comment by grochowskia** [comment]
Thanks Matt, good intro...

**Comment by rajp3126** [comment]
Thanks Matt !! Very good intro !! This is Raj :)

**Comment by acs13** [comment]
Hey Matt, great presentation! Thank you for it. 

This is Aline, a newbie in GitHub :)
